# Generated by Django 3.1.7 on 2021-03-05 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thewall', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='image/profile.png', upload_to='image/'),
        ),
    ]
